name: ChunkClaim
version: '1.0-SNAPSHOT'
main: chunkers.chunkClaim.ChunkClaim
api-version: '1.20'
commands:
  claim:
    description: "Claim a chunk of land."
    usage: "/claim"
  who:
    description: "wem gehört der chunk?"
    usage: "/who"
